python_binary(
    name = "tools",
    main = "cli.py",
    deps = [
        "//third_party/python:click",
        "//tools/package:to_build",
        "//tools/package:to_req",
    ],
    visibility = ["PUBLIC"],
)
